# Generated by Django 5.1.1 on 2024-09-29 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0003_remove_income_date_income_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-amount']},
        ),
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('name', 'owner')},
        ),
    ]
