# Generated by Django 5.1.1 on 2024-09-29 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0004_alter_income_options_income_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='income',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
