# Generated by Django 5.1.1 on 2024-09-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0006_alter_income_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
