# Generated by Django 5.1.1 on 2024-09-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0007_alter_income_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['amount']},
        ),
    ]
